REGRESSION(302346@main): [GTK] ScrollbarThemeGtk.h:48:220: error: non-virtual member function marked 'override' hides virtual member function https://bugs.webkit.org/show_bug.cgi?id=303011
Reviewed by Fujii Hironori.

This function has one fewer parameter now. It wasn't being used, anyway.

Canonical link: https://commits.webkit.org/303538@main