Unreviewed, reverting 301088@main (2da6c3d7fc14) https://bugs.webkit.org/show_bug.cgi?id=300268 rdar://162073550
REGRESSION(301069@main): broke internal builds

Reverted change:

    ModelProcessModelPlayerManager.cpp:64:13: error: reference to stack memory associated with local variable 'modelProcessConnection' returned
    https://bugs.webkit.org/show_bug.cgi?id=300260
    rdar://162066538
    301088@main (2da6c3d7fc14)

Canonical link: https://commits.webkit.org/301107@main