Fix the build after 309850@main https://bugs.webkit.org/show_bug.cgi?id=310650 rdar://173260572
Unreviewed build fix for missing semicolon:

    Source/JavaScriptCore/wasm/WasmOperations.h:94:132: error: expected ';' after top level declarator
       94 | JSC_DECLARE_NOEXCEPT_JIT_OPERATION(operationWasmMemorySizeInPages, int64_t, (JSWebAssemblyInstance* instance, uint8_t memoryIndex))

* Source/JavaScriptCore/wasm/WasmOperations.h:

Canonical link: https://commits.webkit.org/309857@main