[GCC] Fix build after 303805@main https://bugs.webkit.org/show_bug.cgi?id=303398
Reviewed by Sam Weinig.

Fix build error in 'RenderrStyleInlines.h':

error: call to non-‘constexpr’ function ‘WebCore::DisplayType WebCore::RenderStyle::display() const’

Changeset '303805@main' removed 'constexpr' modifier in declaration of
'RenderStyle::display'. GCC12 requires this function to be declared with a
'constexpr' modifier.

* Source/WebCore/css/scripts/process-css-properties.py:
* Source/WebCore/rendering/style/RenderStyle.h:

Canonical link: https://commits.webkit.org/303918@main