[macOS arm64] inspector/unit-tests/array-utilities.html is a flaky text/timeout failure rdar://172695961 https://bugs.webkit.org/show_bug.cgi?id=310052
Reviewed by BJ Burg.

Inconsistent logging from expectException() is causing flaky text failures on
release, looks like this is timing related since it occurs on tests ran with --run-singly.
Test also times out on debug due to large amounts of allocations.

Both:
- TypeError: {} is not iterable - Expected
- TypeError: undefined is not a function (near '...item of iterable...') - Actual
Are valid outputs since they raise TypeError however, the test harness does not account for this.

Fixes:
- Manual try/catch that asserts e instanceof TypeError, validating the error type programmatically
rather than matching the message string.
- Mark test slow on debug to address timeouts

* LayoutTests/inspector/unit-tests/array-utilities-expected.txt:
* LayoutTests/inspector/unit-tests/array-utilities.html:
* LayoutTests/platform/mac-wk2/TestExpectations:

Canonical link: https://commits.webkit.org/309385@main